CREATE DATABASE roundcube DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE junox DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE USER '#_MYSQL:USERNAME_#'@localhost IDENTIFIED BY '#_MYSQL:PASSWORD_#';
GRANT ALL PRIVILEGES ON *.* TO '#_MYSQL:USERNAME_#'@'localhost' IDENTIFIED BY '#_MYSQL:PASSWORD_#';
FLUSH PRIVILEGES;
